# docker-compose.yml
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - math_network

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - math_network
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Only API Gateway is exposed to host
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - RABBITMQ_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      auth-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - math_network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
    # No ports exposed to host - only internal access
    networks:
      - math_network
    depends_on:
      - redis

  addition-service:
    build:
      context: ./addition-service
      dockerfile: Dockerfile
    environment:
      - AMQP_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - math_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  multiplication-service:
    build:
      context: ./multiplication-service
      dockerfile: Dockerfile
    environment:
      - AMQP_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - math_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 3

networks:
  math_network:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data: